Drop Elixir 1.14 support due to binary pattern updates
Elixir 1.14 will fail to build due to:

```
== Compilation error in file lib/atecc508a/transport/i2c_server.ex ==
** (CompileError) lib/atecc508a/transport/i2c_server.ex:206: cannot use ^payload_length outside of match clauses
    (elixir 1.14.2) src/elixir_bitstring.erl:254: :elixir_bitstring.expand_spec_arg/4
    (elixir 1.14.2) src/elixir_bitstring.erl:190: :elixir_bitstring.expand_each_spec/6
    (elixir 1.14.2) src/elixir_bitstring.erl:160: :elixir_bitstring.expand_specs/7
    (elixir 1.14.2) src/elixir_bitstring.erl:38: :elixir_bitstring.expand/8
    (elixir 1.14.2) src/elixir_bitstring.erl:14: :elixir_bitstring.expand/5
```